server:
  port: 8080
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
multitenancy:
  master:
    datasource:
      url: jdbc:mysql://localhost:3306/blog
      username: root
      password: 123456@a
    liquibase:
      enabled: true
      changeLog: classpath:db/changelog/db.changelog-tenant.yaml
